**LIFE CYCLE OF DATA SCIENCE**

                                  Data read
                                      |
                                  Data cleaning
                                      |
                                  Data Analysis
                                      |
                                  Feature engineering
                                      |
                                  Feature selection
                                      |
                                  Model development
                                      |
                                  Model evaluation
                                      |
                                  Model tuning
                                      |
                                  Model deployment

**Feature Engineering**

- so far we have performed feature analysis

    - Data frame quick checks
 
    - Categorical column analysis
 
    - Bar charts, Pie charts
 
    - Numerical column analysis
 
    - Histogram, box plot, outliers
 
    - Bi-multi variate analysis
 
    - correlation etc
 
- Now we need to learn Feature Engineering

    - we will create a new columns for better ML models
 
    - we will perform the **Encoding**, which is convert categorical to numerical data
 
    - we will do data **transformations**
 
    - we will perform **scalling: Standardization and Normalization**
 
    - we will perform the **missing value analysis**
 
- Simply feature engineering means our data will be modified

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r"C:\Users\HP\Documents\NareshIT\Data_Files\Visadataset.csv")
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [8]:
import pandas as pd

**Case_status**

In [9]:
# first check how many unique lables are there in case_status
visa_df['case_status']
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [10]:
# crate a dictionary
d ={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [11]:
# map the above the dictionary with original column
visa_df['case_status']=visa_df['case_status'].map(d)  # dictionay d

In [12]:
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [8]:
labels=sorted(visa_df['education_of_employee'].unique())
d={j:i for i,j in enumerate(labels)}
visa_df['education_of_employee'].map(d)

0        2
1        3
2        0
3        0
4        3
        ..
25475    0
25476    2
25477    3
25478    3
25479    0
Name: education_of_employee, Length: 25480, dtype: int64

In [9]:
d

{"Bachelor's": 0, 'Doctorate': 1, 'High School': 2, "Master's": 3}

- there are two rn==encodings

    - LabelEncoder

    - OrdinalEncoder

**Tyoes of encoders**

Education     LabelEncoder       OrdinalEncoder
====================================================
HighSchool      1                   0

Bachelor        0                   1

Masters         2                   2

PH.D            3                   3


1   0   2   3 ===> ML model sees this: 3>2>1>0
which indicates: PH.D>Master>HighSchool>Bachelor

In [ ]:
# read the data
visa_df=pd.read_csv(r"C:\Users\HP\Documents\NareshIT\Data_Files\Visadataset.csv")

In [14]:
import sklearn
dir(sklearn)

['calibration',
 'clone',
 'cluster',
 'compose',
 'config_context',
 'covariance',
 'cross_decomposition',
 'datasets',
 'decomposition',
 'discriminant_analysis',
 'dummy',
 'ensemble',
 'exceptions',
 'experimental',
 'externals',
 'feature_extraction',
 'feature_selection',
 'frozen',
 'gaussian_process',
 'get_config',
 'impute',
 'inspection',
 'isotonic',
 'kernel_approximation',
 'kernel_ridge',
 'linear_model',
 'manifold',
 'metrics',
 'mixture',
 'model_selection',
 'multiclass',
 'multioutput',
 'naive_bayes',
 'neighbors',
 'neural_network',
 'pipeline',
 'preprocessing',
 'random_projection',
 'semi_supervised',
 'set_config',
 'show_versions',
 'svm',
 'tree']

In [ ]:
- sklearn: **Package**

    - preprocessing: **module**

        - LabelEncoder: **class**

             - fit_transform: **method**

import sklearn
sklearn.preprocessing

from sklearn import preprocessing
dir(preproceesing): LabelEncoder
preprocessing.LableEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform()


# Read the class
# save the class
# apply the fit transform

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform()

**fit transform**    

- fit: created a dictionary(find something)

- transform: using above finding we are modify the data

from sklearn.module import class

va=class()

va.fit or va.fit_transform

 interview que what is fit and what is transform

In [ ]:
# 11-8-26

In [11]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**LabelEncoder**

In [1]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
visa_df['casw_status']=le.fit_transform(visa_df['case_status'])

NameError: name 'le' is not defined

In [17]:
# Read the data again
visa_df=pd.read_csv(r"C:\Users\HP\Documents\NareshIT\Data_Files\Visadataset.csv")

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:    # Dont consider case id
    visa_df[i]=le.fit_transform(visa_df[i])

In [19]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [ ]:
# interview que what is ordinal_column vs label_column when to use ordinal column when to use
# label column most imp for interview que

In [ ]:
# Read the data again
visa_df=pd.read_csv(r"C:\Users\HP\Documents\NareshIT\Data_Files\Visadataset.csv")

In [24]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
for i in cat[1:]:    # Dont consider case id
    visa_df[i]=oe.fit_transform(visa_df[[i]])

In [25]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

In [26]:
# Read the data again
visa_df=pd.read_csv(r"C:\Users\HP\Documents\NareshIT\Data_Files\Visadataset.csv")

**pd.get_dummies**

- get dummies is a way to represent the categorical columns to numerical

- first it will check what are the labels in a column

- for example case status has two labels

    - Denied and Certified

- So it will create two new columns based on labels

    - col1: case_status_Denied
    - col2: case_status_Certified


  case_Status|  case_status_Denied| Case_status_Certified
     -       |           -         |          -
  Denied     |           1         |          0
  Certified  |           0         |          1
  Certified  |           0         |          1


**It is also called as One Hot Encoder**

- It makes new columns are independent each other

- some of ML algorithms expect that columns should be independent each other

In [27]:
pd.get_dummies(visa_df['case_status'],
               dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]